name: Публикация проекта на Github Pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Установка Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "latest"
      - name: Установка Node зависимостей
        run: npm install
      - name: Установка Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true
      - name: Сборка Hugo
        run: hugo --minify
      - name: Размещение на GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
